/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Toolshop API
 * Toolshop REST API technical description
 * OpenAPI spec version: 5.0.0
 */
import * as zod from 'zod';

/**
 * Retrieve all brands
 * @summary Retrieve all brands
 */
export const GetBrandsResponseItem = zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "slug": zod.string().optional()
})
export const GetBrandsResponse = zod.array(GetBrandsResponseItem)


/**
 * Store new brand
 * @summary Store new brand
 */
export const StoreBrandBody = zod.object({
  "name": zod.string(),
  "slug": zod.string().describe('URL part, words separated by hyphen')
})

export const StoreBrandResponse = zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "slug": zod.string().optional()
})


/**
 * Retrieve specific brand
 * @summary Retrieve specific brand
 */
export const GetBrandParams = zod.object({
  "brandId": zod.string().describe('The brandId parameter in path')
})

export const GetBrandResponse = zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "slug": zod.string().optional()
})


/**
 * Update specific brand
 * @summary Update specific brand
 */
export const UpdateBrandParams = zod.object({
  "brandId": zod.string().describe('The brandId parameter in path')
})

export const UpdateBrandBody = zod.object({
  "name": zod.string(),
  "slug": zod.string().describe('URL part, words separated by hyphen')
})

export const UpdateBrandResponse = zod.strictObject({
  "success": zod.boolean()
})


/**
 * Admin role is required to delete a specific brand
 * @summary Delete specific brand
 */
export const DeleteBrandParams = zod.object({
  "brandId": zod.string().describe('The brandId parameter in path')
})

export const DeleteBrandResponse = zod.void()


/**
 * Partially update specific brand
 * @summary Partially update specific brand
 */
export const PatchBrandParams = zod.object({
  "brandId": zod.string().describe('The brandId parameter in path')
})

export const PatchBrandBody = zod.object({
  "name": zod.string(),
  "slug": zod.string().describe('URL part, words separated by hyphen')
})

export const PatchBrandResponse = zod.strictObject({
  "success": zod.boolean()
})


/**
 * Search is performed on the `name` column
 * @summary Retrieve specific brands matching the search query
 */
export const SearchBrandQueryParams = zod.object({
  "q": zod.string().describe('A query phrase')
})

export const SearchBrandResponseItem = zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "slug": zod.string().optional()
})
export const SearchBrandResponse = zod.array(SearchBrandResponseItem)


/**
 * Create a new cart
 * @summary Create a new cart
 */
export const CreateCartResponse = zod.strictObject({
  "id": zod.string()
})


/**
 * Add item to cart
 * @summary Add item to cart
 */
export const AddItemParams = zod.object({
  "id": zod.string().describe('Cart ID')
})

export const AddItemBody = zod.object({
  "product_id": zod.string(),
  "quantity": zod.number()
})

export const AddItemResponse = zod.strictObject({
  "result": zod.string()
})


/**
 * Retrieve specific cart
 * @summary Retrieve specific cart
 */
export const GetCartParams = zod.object({
  "cartId": zod.string().describe('The cartId parameter in path')
})

export const GetCartResponse = zod.strictObject({
  "id": zod.string()
})


/**
 * Delete Cart
 * @summary Delete Cart
 */
export const DeleteCartParams = zod.object({
  "cartId": zod.string().describe('The cartId parameter in path')
})

export const DeleteCartResponse = zod.void()


/**
 * Update quantity of item in cart
 * @summary Update quantity of item in cart
 */
export const UpdateCartQuantityParams = zod.object({
  "cartId": zod.string().describe('Cart ID')
})

export const UpdateCartQuantityBody = zod.object({
  "product_id": zod.string(),
  "quantity": zod.number()
})

export const UpdateCartQuantityResponse = zod.strictObject({
  "success": zod.boolean()
})


/**
 * Delete a product from Cart
 * @summary Delete product from cart
 */
export const DeleteProductFromCartParams = zod.object({
  "cartId": zod.string().describe('The cartId parameter in path'),
  "productId": zod.string().describe('The cartId parameter in path')
})

export const DeleteProductFromCartResponse = zod.void()


/**
 * Retrieve all categories (including subcategories)
 * @summary Retrieve all categories (including subcategories)
 */
export const GetCategoriesTreeQueryParams = zod.object({
  "by_category_slug": zod.string().optional().describe('Parent category slug')
})

export const GetCategoriesTreeResponseItem = zod.strictObject({
  "id": zod.string(),
  "parent_id": zod.string().nullable(),
  "name": zod.string(),
  "slug": zod.string(),
  "sub_categories": zod.array(zod.strictObject({
  "id": zod.string(),
  "parent_id": zod.string().nullish(),
  "name": zod.string(),
  "slug": zod.string().optional(),
  "sub_categories": zod.array(zod.unknown()).optional()
}))
})
export const GetCategoriesTreeResponse = zod.array(GetCategoriesTreeResponseItem)


/**
 * Retrieve all categories
 * @summary Retrieve all categories
 */
export const GetCategoriesResponseItem = zod.strictObject({
  "id": zod.string(),
  "parent_id": zod.string().nullish(),
  "name": zod.string(),
  "slug": zod.string().optional(),
  "sub_categories": zod.array(zod.unknown()).optional()
})
export const GetCategoriesResponse = zod.array(GetCategoriesResponseItem)


/**
 * Store new category
 * @summary Store new category
 */
export const StoreCategoryBody = zod.object({
  "name": zod.string(),
  "slug": zod.string().describe('URL part, words separated by hyphen'),
  "parent_id": zod.string().nullable()
})

export const StoreCategoryResponse = zod.strictObject({
  "id": zod.string(),
  "parent_id": zod.string().nullish(),
  "name": zod.string(),
  "slug": zod.string().optional(),
  "sub_categories": zod.array(zod.unknown()).optional()
})


/**
 * Retrieve specific category (including subcategories)
 * @summary Retrieve specific category (including subcategories)
 */
export const GetCategoryParams = zod.object({
  "categoryId": zod.string().describe('The categoryId parameter in path')
})

export const GetCategoryResponse = zod.strictObject({
  "id": zod.string(),
  "parent_id": zod.string().nullable(),
  "name": zod.string(),
  "slug": zod.string(),
  "sub_categories": zod.array(zod.strictObject({
  "id": zod.string(),
  "parent_id": zod.string().nullish(),
  "name": zod.string(),
  "slug": zod.string().optional(),
  "sub_categories": zod.array(zod.unknown()).optional()
}))
})


/**
 * Search is performed on the `name` column
 * @summary Retrieve specific categories matching the search query
 */
export const SearchCategoryQueryParams = zod.object({
  "q": zod.string().describe('A query phrase')
})

export const SearchCategoryResponseItem = zod.strictObject({
  "id": zod.string(),
  "parent_id": zod.string().nullish(),
  "name": zod.string(),
  "slug": zod.string().optional(),
  "sub_categories": zod.array(zod.unknown()).optional()
})
export const SearchCategoryResponse = zod.array(SearchCategoryResponseItem)


/**
 * Update specific category
 * @summary Update specific category
 */
export const UpdateCategoryParams = zod.object({
  "categoryId": zod.string().describe('The categoryId parameter in path')
})

export const UpdateCategoryBody = zod.object({
  "name": zod.string(),
  "slug": zod.string().describe('URL part, words separated by hyphen'),
  "parent_id": zod.string().nullable()
})

export const UpdateCategoryResponse = zod.strictObject({
  "success": zod.boolean()
})


/**
 * Admin role is required to delete a specific category
 * @summary Delete specific category
 */
export const DeleteCategoryParams = zod.object({
  "categoryId": zod.string().describe('The categoryId parameter in path')
})

export const DeleteCategoryResponse = zod.void()


/**
 * Partially update specific category
 * @summary Partially update specific category
 */
export const PatchCategoryParams = zod.object({
  "categoryId": zod.string().describe('The categoryId parameter in path')
})

export const PatchCategoryBody = zod.object({
  "name": zod.string(),
  "slug": zod.string().describe('URL part, words separated by hyphen'),
  "parent_id": zod.string().nullable()
})

export const PatchCategoryResponse = zod.strictObject({
  "success": zod.boolean()
})


/**
 * `admin` retrieves all messages, `user` retrieves only related messages
 * @summary Retrieve messages
 */
export const GetMessagesQueryParams = zod.object({
  "page": zod.number().optional().describe('pagenumber')
})

export const GetMessagesResponse = zod.strictObject({
  "current_page": zod.number(),
  "data": zod.array(zod.union([zod.strictObject({
  "name": zod.string(),
  "email": zod.string(),
  "subject": zod.string(),
  "message": zod.string(),
  "status": zod.string(),
  "id": zod.string(),
  "created_at": zod.string()
}),zod.strictObject({
  "user_id": zod.string(),
  "name": zod.string(),
  "email": zod.string(),
  "subject": zod.string(),
  "message": zod.string(),
  "status": zod.string(),
  "id": zod.string(),
  "created_at": zod.string()
})])),
  "from": zod.number(),
  "last_page": zod.number(),
  "per_page": zod.number(),
  "to": zod.number(),
  "total": zod.number()
})


/**
 * Send new contact message by mail
 * @summary Send new contact message
 */
export const sendMessageBodyNameMax = 120;

export const sendMessageBodyEmailMax = 256;

export const sendMessageBodySubjectMax = 120;

export const sendMessageBodyMessageMax = 250;



export const SendMessageBody = zod.object({
  "name": zod.string().max(sendMessageBodyNameMax).optional().describe('Sender name'),
  "email": zod.string().max(sendMessageBodyEmailMax).optional().describe('Required when not authenticated'),
  "subject": zod.string().max(sendMessageBodySubjectMax),
  "message": zod.string().max(sendMessageBodyMessageMax)
})

export const SendMessageResponse = zod.strictObject({
  "success": zod.boolean()
})


/**
 * Attach file to contact message
 * @summary Attach file to contact message
 */
export const AttachFileParams = zod.object({
  "messageId": zod.string().describe('The messageId parameter in path')
})

export const AttachFileBody = zod.object({
  "file": zod.instanceof(File).describe('File')
})

export const AttachFileResponse = zod.strictObject({
  "success": zod.boolean()
})


/**
 * Retrieve specific message
 * @summary Retrieve specific message
 */
export const GetMessageParams = zod.object({
  "messageId": zod.string().describe('The messageId parameter in path')
})

export const GetMessageResponse = zod.union([zod.strictObject({
  "name": zod.string(),
  "email": zod.string(),
  "subject": zod.string(),
  "message": zod.string(),
  "status": zod.string(),
  "id": zod.string(),
  "created_at": zod.string()
}),zod.strictObject({
  "user_id": zod.string(),
  "name": zod.string(),
  "email": zod.string(),
  "subject": zod.string(),
  "message": zod.string(),
  "status": zod.string(),
  "id": zod.string(),
  "created_at": zod.string()
})])


/**
 * Send new contact message by mail
 * @summary Send new contact message
 */
export const ReplyToMessageParams = zod.object({
  "messageId": zod.string().describe('The messageId parameter in path')
})

export const replyToMessageBodyNameMax = 120;

export const replyToMessageBodyEmailMax = 256;

export const replyToMessageBodySubjectMax = 120;

export const replyToMessageBodyMessageMax = 250;



export const ReplyToMessageBody = zod.object({
  "name": zod.string().max(replyToMessageBodyNameMax).optional().describe('Sender name'),
  "email": zod.string().max(replyToMessageBodyEmailMax).optional().describe('Required when not authenticated'),
  "subject": zod.string().max(replyToMessageBodySubjectMax),
  "message": zod.string().max(replyToMessageBodyMessageMax)
})

export const ReplyToMessageResponse = zod.strictObject({
  "message": zod.string(),
  "id": zod.string(),
  "created_at": zod.string(),
  "user": zod.strictObject({
  "first_name": zod.string(),
  "last_name": zod.string(),
  "address": zod.strictObject({
  "street": zod.string(),
  "house_number": zod.string().nullable(),
  "city": zod.string(),
  "state": zod.string().nullable(),
  "country": zod.string(),
  "postal_code": zod.string().nullable()
}),
  "phone": zod.string().nullable(),
  "dob": zod.string(),
  "email": zod.string(),
  "id": zod.string(),
  "provider": zod.string().nullable(),
  "totp_enabled": zod.boolean(),
  "enabled": zod.boolean(),
  "failed_login_attempts": zod.number().nullable(),
  "created_at": zod.string()
})
})


/**
 * Set a new message status. Possible values: `NEW`, `IN_PROGRESS`, `RESOLVED`
 * @summary Set a new message status
 */
export const UpdateMessageStatusParams = zod.object({
  "messageId": zod.string().describe('The messageId parameter in path')
})

export const UpdateMessageStatusBody = zod.object({
  "status": zod.enum(['NEW', 'ON_HOLD', 'IN_PROGRESS', 'RESOLVED'])
})

export const UpdateMessageStatusResponse = zod.strictObject({
  "success": zod.boolean()
})


/**
 * User role is required to retrieve users favorites
 * @summary Retrieve all favorites
 */
export const GetFavoritesResponseItem = zod.strictObject({
  "product_id": zod.string(),
  "user_id": zod.string(),
  "id": zod.string(),
  "product": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "is_location_offer": zod.boolean(),
  "is_rental": zod.boolean(),
  "in_stock": zod.boolean(),
  "co2_rating": zod.string(),
  "is_eco_friendly": zod.boolean(),
  "brand": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "slug": zod.string().optional()
}),
  "category": zod.strictObject({
  "id": zod.string(),
  "parent_id": zod.string().nullish(),
  "name": zod.string(),
  "slug": zod.string().optional(),
  "sub_categories": zod.array(zod.unknown()).optional()
}),
  "product_image": zod.strictObject({
  "by_name": zod.string(),
  "by_url": zod.string(),
  "source_name": zod.string(),
  "source_url": zod.string(),
  "file_name": zod.string(),
  "title": zod.string(),
  "id": zod.string()
}),
  "specs": zod.array(zod.unknown()).optional()
})
})
export const GetFavoritesResponse = zod.array(GetFavoritesResponseItem)


/**
 * User role is required to store new favorite
 * @summary Store new favorite
 */
export const StoreFavoriteBody = zod.object({
  "product_id": zod.string()
})

export const StoreFavoriteResponse = zod.strictObject({
  "product_id": zod.string(),
  "user_id": zod.string(),
  "id": zod.string()
})


/**
 * User role is required to retrieve specific favorite
 * @summary Retrieve specific favorite
 */
export const GetFavoriteParams = zod.object({
  "favoriteId": zod.string().describe('The favoriteId parameter in path')
})

export const GetFavoriteResponse = zod.strictObject({
  "product_id": zod.string(),
  "user_id": zod.string(),
  "id": zod.string()
})


/**
 * User role is required to delete a specific favorite
 * @summary Delete specific favorite
 */
export const DeleteFavoriteParams = zod.object({
  "favoriteId": zod.string().describe('The favoriteId parameter in path')
})

export const DeleteFavoriteResponse = zod.void()


/**
 * Retrieve all images
 * @summary Retrieve all images
 */
export const GetImagesResponseItem = zod.strictObject({
  "by_name": zod.string(),
  "by_url": zod.string(),
  "source_name": zod.string(),
  "source_url": zod.string(),
  "file_name": zod.string(),
  "title": zod.string(),
  "id": zod.string()
})
export const GetImagesResponse = zod.array(GetImagesResponseItem)


/**
 * `admin` retrieves all invoices, `user` retrieves only related invoices
 * @summary Retrieve all invoices
 */
export const GetInvoicesQueryParams = zod.object({
  "page": zod.number().optional().describe('pagenumber')
})

export const GetInvoicesResponse = zod.strictObject({
  "current_page": zod.number(),
  "data": zod.array(zod.strictObject({
  "id": zod.string(),
  "user_id": zod.string(),
  "invoice_date": zod.string(),
  "invoice_number": zod.string(),
  "billing_street": zod.string(),
  "billing_city": zod.string(),
  "billing_country": zod.string(),
  "billing_state": zod.string(),
  "billing_postal_code": zod.string(),
  "additional_discount_percentage": zod.number(),
  "additional_discount_amount": zod.number(),
  "subtotal": zod.number(),
  "total": zod.number(),
  "status": zod.string(),
  "status_message": zod.string(),
  "invoicelines": zod.array(zod.strictObject({
  "id": zod.string(),
  "invoice_id": zod.string(),
  "product_id": zod.string(),
  "unit_price": zod.number(),
  "discount_percentage": zod.number(),
  "discounted_price": zod.number(),
  "quantity": zod.number(),
  "product": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "is_location_offer": zod.boolean(),
  "is_rental": zod.boolean(),
  "in_stock": zod.boolean(),
  "co2_rating": zod.string(),
  "is_eco_friendly": zod.boolean(),
  "brand": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "slug": zod.string().optional()
}),
  "category": zod.strictObject({
  "id": zod.string(),
  "parent_id": zod.string().nullish(),
  "name": zod.string(),
  "slug": zod.string().optional(),
  "sub_categories": zod.array(zod.unknown()).optional()
}),
  "product_image": zod.strictObject({
  "by_name": zod.string(),
  "by_url": zod.string(),
  "source_name": zod.string(),
  "source_url": zod.string(),
  "file_name": zod.string(),
  "title": zod.string(),
  "id": zod.string()
}),
  "specs": zod.array(zod.unknown()).optional()
})
})),
  "created_at": zod.string()
})),
  "from": zod.number(),
  "last_page": zod.number(),
  "per_page": zod.number(),
  "to": zod.number(),
  "total": zod.number()
})


/**
 * Store new invoice
 * @summary Store new invoice
 */
export const StoreInvoiceBody = zod.object({
  "billing_street": zod.string(),
  "billing_city": zod.string(),
  "billing_state": zod.string(),
  "billing_country": zod.string(),
  "billing_postal_code": zod.string(),
  "payment_method": zod.enum(['bank-transfer', 'cash-on-delivery', 'credit-card', 'buy-now-pay-later', 'gift-card']),
  "cart_id": zod.string(),
  "payment_details": zod.union([zod.object({
  "bank_name": zod.string(),
  "account_name": zod.string(),
  "account_number": zod.string()
}),zod.object({
  "credit_card_number": zod.string(),
  "expiration_date": zod.string(),
  "cvv": zod.string(),
  "card_holder_name": zod.string()
}),zod.object({
  "gift_card_number": zod.string(),
  "validation_code": zod.string()
}),zod.object({
  "monthly_installments": zod.string()
}),zod.looseObject({

})])
})

export const StoreInvoiceResponse = zod.strictObject({
  "id": zod.string(),
  "user_id": zod.string(),
  "invoice_date": zod.string(),
  "invoice_number": zod.string(),
  "billing_street": zod.string(),
  "billing_city": zod.string(),
  "billing_country": zod.string(),
  "billing_state": zod.string(),
  "billing_postal_code": zod.string(),
  "additional_discount_percentage": zod.number(),
  "additional_discount_amount": zod.number(),
  "subtotal": zod.number(),
  "total": zod.number(),
  "status": zod.string(),
  "status_message": zod.string(),
  "invoicelines": zod.array(zod.strictObject({
  "id": zod.string(),
  "invoice_id": zod.string(),
  "product_id": zod.string(),
  "unit_price": zod.number(),
  "discount_percentage": zod.number(),
  "discounted_price": zod.number(),
  "quantity": zod.number(),
  "product": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "is_location_offer": zod.boolean(),
  "is_rental": zod.boolean(),
  "in_stock": zod.boolean(),
  "co2_rating": zod.string(),
  "is_eco_friendly": zod.boolean(),
  "brand": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "slug": zod.string().optional()
}),
  "category": zod.strictObject({
  "id": zod.string(),
  "parent_id": zod.string().nullish(),
  "name": zod.string(),
  "slug": zod.string().optional(),
  "sub_categories": zod.array(zod.unknown()).optional()
}),
  "product_image": zod.strictObject({
  "by_name": zod.string(),
  "by_url": zod.string(),
  "source_name": zod.string(),
  "source_url": zod.string(),
  "file_name": zod.string(),
  "title": zod.string(),
  "id": zod.string()
}),
  "specs": zod.array(zod.unknown()).optional()
})
})),
  "created_at": zod.string()
})


/**
 * Store new invoice for guest checkout
 * @summary Store new guest invoice
 */
export const StoreGuestInvoiceBody = zod.object({
  "billing_street": zod.string(),
  "billing_city": zod.string(),
  "billing_state": zod.string(),
  "billing_country": zod.string(),
  "billing_postal_code": zod.string(),
  "payment_method": zod.enum(['bank-transfer', 'cash-on-delivery', 'credit-card', 'buy-now-pay-later', 'gift-card']),
  "cart_id": zod.string(),
  "payment_details": zod.union([zod.object({
  "bank_name": zod.string(),
  "account_name": zod.string(),
  "account_number": zod.string()
}),zod.object({
  "credit_card_number": zod.string(),
  "expiration_date": zod.string(),
  "cvv": zod.string(),
  "card_holder_name": zod.string()
}),zod.object({
  "gift_card_number": zod.string(),
  "validation_code": zod.string()
}),zod.object({
  "monthly_installments": zod.string()
}),zod.looseObject({

})])
}).and(zod.object({
  "guest_email": zod.email().describe('Guest email address'),
  "guest_first_name": zod.string().describe('Guest first name'),
  "guest_last_name": zod.string().describe('Guest last name')
}))

export const StoreGuestInvoiceResponse = zod.strictObject({
  "id": zod.string(),
  "user_id": zod.string(),
  "invoice_date": zod.string(),
  "invoice_number": zod.string(),
  "billing_street": zod.string(),
  "billing_city": zod.string(),
  "billing_country": zod.string(),
  "billing_state": zod.string(),
  "billing_postal_code": zod.string(),
  "additional_discount_percentage": zod.number(),
  "additional_discount_amount": zod.number(),
  "subtotal": zod.number(),
  "total": zod.number(),
  "status": zod.string(),
  "status_message": zod.string(),
  "invoicelines": zod.array(zod.strictObject({
  "id": zod.string(),
  "invoice_id": zod.string(),
  "product_id": zod.string(),
  "unit_price": zod.number(),
  "discount_percentage": zod.number(),
  "discounted_price": zod.number(),
  "quantity": zod.number(),
  "product": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "is_location_offer": zod.boolean(),
  "is_rental": zod.boolean(),
  "in_stock": zod.boolean(),
  "co2_rating": zod.string(),
  "is_eco_friendly": zod.boolean(),
  "brand": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "slug": zod.string().optional()
}),
  "category": zod.strictObject({
  "id": zod.string(),
  "parent_id": zod.string().nullish(),
  "name": zod.string(),
  "slug": zod.string().optional(),
  "sub_categories": zod.array(zod.unknown()).optional()
}),
  "product_image": zod.strictObject({
  "by_name": zod.string(),
  "by_url": zod.string(),
  "source_name": zod.string(),
  "source_url": zod.string(),
  "file_name": zod.string(),
  "title": zod.string(),
  "id": zod.string()
}),
  "specs": zod.array(zod.unknown()).optional()
})
})),
  "created_at": zod.string()
})


/**
 * Retrieve specific invoice
 * @summary Retrieve specific invoice
 */
export const GetInvoiceParams = zod.object({
  "invoiceId": zod.string().describe('The invoiceId parameter in path')
})

export const GetInvoiceResponse = zod.strictObject({
  "id": zod.string(),
  "user_id": zod.string(),
  "invoice_date": zod.string(),
  "invoice_number": zod.string(),
  "billing_street": zod.string(),
  "billing_city": zod.string(),
  "billing_country": zod.string(),
  "billing_state": zod.string(),
  "billing_postal_code": zod.string(),
  "additional_discount_percentage": zod.number(),
  "additional_discount_amount": zod.number(),
  "subtotal": zod.number(),
  "total": zod.number(),
  "status": zod.string(),
  "status_message": zod.string(),
  "invoicelines": zod.array(zod.strictObject({
  "id": zod.string(),
  "invoice_id": zod.string(),
  "product_id": zod.string(),
  "unit_price": zod.number(),
  "discount_percentage": zod.number(),
  "discounted_price": zod.number(),
  "quantity": zod.number(),
  "product": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "is_location_offer": zod.boolean(),
  "is_rental": zod.boolean(),
  "in_stock": zod.boolean(),
  "co2_rating": zod.string(),
  "is_eco_friendly": zod.boolean(),
  "brand": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "slug": zod.string().optional()
}),
  "category": zod.strictObject({
  "id": zod.string(),
  "parent_id": zod.string().nullish(),
  "name": zod.string(),
  "slug": zod.string().optional(),
  "sub_categories": zod.array(zod.unknown()).optional()
}),
  "product_image": zod.strictObject({
  "by_name": zod.string(),
  "by_url": zod.string(),
  "source_name": zod.string(),
  "source_url": zod.string(),
  "file_name": zod.string(),
  "title": zod.string(),
  "id": zod.string()
}),
  "specs": zod.array(zod.unknown()).optional()
})
})),
  "created_at": zod.string()
})


/**
 * Update specific invoice
 * @summary Update specific invoice
 */
export const UpdateInvoiceParams = zod.object({
  "invoiceId": zod.string().describe('The invoiceId parameter in path')
})

export const UpdateInvoiceBody = zod.object({
  "billing_street": zod.string(),
  "billing_city": zod.string(),
  "billing_state": zod.string(),
  "billing_country": zod.string(),
  "billing_postal_code": zod.string(),
  "payment_method": zod.enum(['bank-transfer', 'cash-on-delivery', 'credit-card', 'buy-now-pay-later', 'gift-card']),
  "cart_id": zod.string(),
  "payment_details": zod.union([zod.object({
  "bank_name": zod.string(),
  "account_name": zod.string(),
  "account_number": zod.string()
}),zod.object({
  "credit_card_number": zod.string(),
  "expiration_date": zod.string(),
  "cvv": zod.string(),
  "card_holder_name": zod.string()
}),zod.object({
  "gift_card_number": zod.string(),
  "validation_code": zod.string()
}),zod.object({
  "monthly_installments": zod.string()
}),zod.looseObject({

})])
})

export const UpdateInvoiceResponse = zod.strictObject({
  "success": zod.boolean()
})


/**
 * Partially update specific invoice
 * @summary Partially update specific invoice
 */
export const PatchInvoiceParams = zod.object({
  "invoiceId": zod.string().describe('The invoiceId parameter in path')
})

export const PatchInvoiceBody = zod.object({
  "billing_street": zod.string(),
  "billing_city": zod.string(),
  "billing_state": zod.string(),
  "billing_country": zod.string(),
  "billing_postal_code": zod.string(),
  "payment_method": zod.enum(['bank-transfer', 'cash-on-delivery', 'credit-card', 'buy-now-pay-later', 'gift-card']),
  "cart_id": zod.string(),
  "payment_details": zod.union([zod.object({
  "bank_name": zod.string(),
  "account_name": zod.string(),
  "account_number": zod.string()
}),zod.object({
  "credit_card_number": zod.string(),
  "expiration_date": zod.string(),
  "cvv": zod.string(),
  "card_holder_name": zod.string()
}),zod.object({
  "gift_card_number": zod.string(),
  "validation_code": zod.string()
}),zod.object({
  "monthly_installments": zod.string()
}),zod.looseObject({

})])
})

export const PatchInvoiceResponse = zod.strictObject({
  "success": zod.boolean()
})


/**
 * Download already generated PDF of a specific invoice
 * @summary Download already generated PDF of a specific invoice
 */
export const DownloadPDFParams = zod.object({
  "invoice_number": zod.string().describe('The invoice_number parameter in path')
})

export const DownloadPDFResponse = zod.strictObject({
  "id": zod.string(),
  "user_id": zod.string(),
  "invoice_date": zod.string(),
  "invoice_number": zod.string(),
  "billing_street": zod.string(),
  "billing_city": zod.string(),
  "billing_country": zod.string(),
  "billing_state": zod.string(),
  "billing_postal_code": zod.string(),
  "additional_discount_percentage": zod.number(),
  "additional_discount_amount": zod.number(),
  "subtotal": zod.number(),
  "total": zod.number(),
  "status": zod.string(),
  "status_message": zod.string(),
  "invoicelines": zod.array(zod.strictObject({
  "id": zod.string(),
  "invoice_id": zod.string(),
  "product_id": zod.string(),
  "unit_price": zod.number(),
  "discount_percentage": zod.number(),
  "discounted_price": zod.number(),
  "quantity": zod.number(),
  "product": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "is_location_offer": zod.boolean(),
  "is_rental": zod.boolean(),
  "in_stock": zod.boolean(),
  "co2_rating": zod.string(),
  "is_eco_friendly": zod.boolean(),
  "brand": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "slug": zod.string().optional()
}),
  "category": zod.strictObject({
  "id": zod.string(),
  "parent_id": zod.string().nullish(),
  "name": zod.string(),
  "slug": zod.string().optional(),
  "sub_categories": zod.array(zod.unknown()).optional()
}),
  "product_image": zod.strictObject({
  "by_name": zod.string(),
  "by_url": zod.string(),
  "source_name": zod.string(),
  "source_url": zod.string(),
  "file_name": zod.string(),
  "title": zod.string(),
  "id": zod.string()
}),
  "specs": zod.array(zod.unknown()).optional()
})
})),
  "created_at": zod.string()
})


/**
 * Retrieve the status of the PDF. The status can be INITIATED, IN_PROGRESS, COMPLETED
 * @summary Retrieve the status of the PDF.
 */
export const DownloadPDFStatusParams = zod.object({
  "invoice_number": zod.string().describe('The invoice_number parameter in path')
})

export const DownloadPDFStatusResponse = zod.strictObject({
  "id": zod.string(),
  "user_id": zod.string(),
  "invoice_date": zod.string(),
  "invoice_number": zod.string(),
  "billing_street": zod.string(),
  "billing_city": zod.string(),
  "billing_country": zod.string(),
  "billing_state": zod.string(),
  "billing_postal_code": zod.string(),
  "additional_discount_percentage": zod.number(),
  "additional_discount_amount": zod.number(),
  "subtotal": zod.number(),
  "total": zod.number(),
  "status": zod.string(),
  "status_message": zod.string(),
  "invoicelines": zod.array(zod.strictObject({
  "id": zod.string(),
  "invoice_id": zod.string(),
  "product_id": zod.string(),
  "unit_price": zod.number(),
  "discount_percentage": zod.number(),
  "discounted_price": zod.number(),
  "quantity": zod.number(),
  "product": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "is_location_offer": zod.boolean(),
  "is_rental": zod.boolean(),
  "in_stock": zod.boolean(),
  "co2_rating": zod.string(),
  "is_eco_friendly": zod.boolean(),
  "brand": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "slug": zod.string().optional()
}),
  "category": zod.strictObject({
  "id": zod.string(),
  "parent_id": zod.string().nullish(),
  "name": zod.string(),
  "slug": zod.string().optional(),
  "sub_categories": zod.array(zod.unknown()).optional()
}),
  "product_image": zod.strictObject({
  "by_name": zod.string(),
  "by_url": zod.string(),
  "source_name": zod.string(),
  "source_url": zod.string(),
  "file_name": zod.string(),
  "title": zod.string(),
  "id": zod.string()
}),
  "specs": zod.array(zod.unknown()).optional()
})
})),
  "created_at": zod.string()
})


/**
 * Update invoice status
 * @summary Update invoice status
 */
export const UpdateInvoiceStatusParams = zod.object({
  "invoiceId": zod.string().describe('The invoiceId parameter in path')
})

export const updateInvoiceStatusBodyStatusMessageMin = 5;
export const updateInvoiceStatusBodyStatusMessageMax = 50;



export const UpdateInvoiceStatusBody = zod.object({
  "status": zod.enum(['AWAITING_FULFILLMENT', 'ON_HOLD', 'AWAITING_SHIPMENT', 'SHIPPED', 'COMPLETED']).describe('The status of the order'),
  "status_message": zod.string().min(updateInvoiceStatusBodyStatusMessageMin).max(updateInvoiceStatusBodyStatusMessageMax).nullable().describe('A message describing the status')
})

export const UpdateInvoiceStatusResponse = zod.strictObject({
  "success": zod.boolean()
})


/**
 * Search is performed on the `invoice_number`, `billing_street` and `status` column
 * @summary Retrieve specific invoices matching the search query
 */
export const SearchInvoiceQueryParams = zod.object({
  "q": zod.string().describe('A query phrase'),
  "page": zod.number().optional().describe('pagenumber')
})

export const SearchInvoiceResponse = zod.strictObject({
  "current_page": zod.number(),
  "data": zod.array(zod.strictObject({
  "id": zod.string(),
  "user_id": zod.string(),
  "invoice_date": zod.string(),
  "invoice_number": zod.string(),
  "billing_street": zod.string(),
  "billing_city": zod.string(),
  "billing_country": zod.string(),
  "billing_state": zod.string(),
  "billing_postal_code": zod.string(),
  "additional_discount_percentage": zod.number(),
  "additional_discount_amount": zod.number(),
  "subtotal": zod.number(),
  "total": zod.number(),
  "status": zod.string(),
  "status_message": zod.string(),
  "invoicelines": zod.array(zod.strictObject({
  "id": zod.string(),
  "invoice_id": zod.string(),
  "product_id": zod.string(),
  "unit_price": zod.number(),
  "discount_percentage": zod.number(),
  "discounted_price": zod.number(),
  "quantity": zod.number(),
  "product": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "is_location_offer": zod.boolean(),
  "is_rental": zod.boolean(),
  "in_stock": zod.boolean(),
  "co2_rating": zod.string(),
  "is_eco_friendly": zod.boolean(),
  "brand": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "slug": zod.string().optional()
}),
  "category": zod.strictObject({
  "id": zod.string(),
  "parent_id": zod.string().nullish(),
  "name": zod.string(),
  "slug": zod.string().optional(),
  "sub_categories": zod.array(zod.unknown()).optional()
}),
  "product_image": zod.strictObject({
  "by_name": zod.string(),
  "by_url": zod.string(),
  "source_name": zod.string(),
  "source_url": zod.string(),
  "file_name": zod.string(),
  "title": zod.string(),
  "id": zod.string()
}),
  "specs": zod.array(zod.unknown()).optional()
})
})),
  "created_at": zod.string()
})),
  "from": zod.number(),
  "last_page": zod.number(),
  "per_page": zod.number(),
  "to": zod.number(),
  "total": zod.number()
})


/**
 * Check payment
 * @summary Check payment
 */
export const CheckPaymentBody = zod.object({
  "payment_method": zod.enum(['bank-transfer', 'cash-on-delivery', 'credit-card', 'buy-now-pay-later', 'gift-card']),
  "payment_details": zod.union([zod.object({
  "bank_name": zod.string(),
  "account_name": zod.string(),
  "account_number": zod.string()
}),zod.object({
  "credit_card_number": zod.string(),
  "expiration_date": zod.string(),
  "cvv": zod.string(),
  "card_holder_name": zod.string()
}),zod.object({
  "gift_card_number": zod.string(),
  "validation_code": zod.string()
}),zod.object({
  "monthly_installments": zod.string()
}),zod.looseObject({

})])
})

export const CheckPaymentResponse = zod.strictObject({
  "message": zod.string()
})


/**
 * Returns street, city and state for a given country/postcode/house number. The underlying source is configurable: a local faker driver (default) or an external HTTP service (e.g. a WireMock stub) when POSTCODE_LOOKUP_DRIVER=http.
 * @summary Lookup address details by postcode
 */
export const postcodeLookupQueryCountryMax = 40;

export const postcodeLookupQueryPostcodeMax = 10;

export const postcodeLookupQueryHouseNumberMax = 10;



export const PostcodeLookupQueryParams = zod.object({
  "country": zod.string().max(postcodeLookupQueryCountryMax),
  "postcode": zod.string().max(postcodeLookupQueryPostcodeMax),
  "house_number": zod.string().max(postcodeLookupQueryHouseNumberMax).optional()
})

export const PostcodeLookupResponse = zod.strictObject({
  "street": zod.string(),
  "house_number": zod.string(),
  "city": zod.string(),
  "state": zod.string(),
  "country": zod.string(),
  "postcode": zod.string()
})


/**
 * Retrieve all products
 * @summary Retrieve all products
 */
export const GetProductsQueryParams = zod.object({
  "by_brand": zod.string().optional().describe('Id of brand'),
  "by_category": zod.string().optional().describe('Id of category'),
  "is_rental": zod.string().optional().describe('Indication if we like to retrieve rentals products'),
  "between": zod.string().optional().describe('Can be used to define a price range, like: price,10,30'),
  "sort": zod.string().optional().describe('Can be used to sort based on specific column value, like: name,asc OR name,desc OR price,asc OR price,desc'),
  "page": zod.number().optional().describe('pagenumber')
})

export const GetProductsResponse = zod.strictObject({
  "current_page": zod.number(),
  "data": zod.array(zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "is_location_offer": zod.boolean(),
  "is_rental": zod.boolean(),
  "in_stock": zod.boolean(),
  "co2_rating": zod.string(),
  "is_eco_friendly": zod.boolean(),
  "brand": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "slug": zod.string().optional()
}),
  "category": zod.strictObject({
  "id": zod.string(),
  "parent_id": zod.string().nullish(),
  "name": zod.string(),
  "slug": zod.string().optional(),
  "sub_categories": zod.array(zod.unknown()).optional()
}),
  "product_image": zod.strictObject({
  "by_name": zod.string(),
  "by_url": zod.string(),
  "source_name": zod.string(),
  "source_url": zod.string(),
  "file_name": zod.string(),
  "title": zod.string(),
  "id": zod.string()
}),
  "specs": zod.array(zod.unknown()).optional()
})),
  "from": zod.number(),
  "last_page": zod.number(),
  "per_page": zod.number(),
  "to": zod.number(),
  "total": zod.number()
})


/**
 * Store new product
 * @summary Store new product
 */
export const StoreProductBody = zod.object({
  "name": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "category_id": zod.string(),
  "brand_id": zod.string(),
  "product_image_id": zod.string(),
  "is_location_offer": zod.boolean(),
  "is_rental": zod.boolean(),
  "co2_rating": zod.string()
})

export const StoreProductResponse = zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "is_location_offer": zod.boolean(),
  "is_rental": zod.boolean(),
  "in_stock": zod.boolean(),
  "co2_rating": zod.string(),
  "is_eco_friendly": zod.boolean(),
  "brand": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "slug": zod.string().optional()
}),
  "category": zod.strictObject({
  "id": zod.string(),
  "parent_id": zod.string().nullish(),
  "name": zod.string(),
  "slug": zod.string().optional(),
  "sub_categories": zod.array(zod.unknown()).optional()
}),
  "product_image": zod.strictObject({
  "by_name": zod.string(),
  "by_url": zod.string(),
  "source_name": zod.string(),
  "source_url": zod.string(),
  "file_name": zod.string(),
  "title": zod.string(),
  "id": zod.string()
}),
  "specs": zod.array(zod.unknown()).optional()
})


/**
 * Retrieve specific product
 * @summary Retrieve specific product
 */
export const GetProductParams = zod.object({
  "productId": zod.string().describe('The productId parameter in path')
})

export const GetProductResponse = zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "is_location_offer": zod.boolean(),
  "is_rental": zod.boolean(),
  "in_stock": zod.boolean(),
  "co2_rating": zod.string(),
  "is_eco_friendly": zod.boolean(),
  "brand": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "slug": zod.string().optional()
}),
  "category": zod.strictObject({
  "id": zod.string(),
  "parent_id": zod.string().nullish(),
  "name": zod.string(),
  "slug": zod.string().optional(),
  "sub_categories": zod.array(zod.unknown()).optional()
}),
  "product_image": zod.strictObject({
  "by_name": zod.string(),
  "by_url": zod.string(),
  "source_name": zod.string(),
  "source_url": zod.string(),
  "file_name": zod.string(),
  "title": zod.string(),
  "id": zod.string()
}),
  "specs": zod.array(zod.unknown()).optional()
})


/**
 * Update specific product
 * @summary Update specific product
 */
export const UpdateProductParams = zod.object({
  "productId": zod.string().describe('The productId parameter in path')
})

export const UpdateProductBody = zod.object({
  "name": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "category_id": zod.string(),
  "brand_id": zod.string(),
  "product_image_id": zod.string(),
  "is_location_offer": zod.boolean(),
  "is_rental": zod.boolean(),
  "co2_rating": zod.string()
})

export const UpdateProductResponse = zod.strictObject({
  "success": zod.boolean()
})


/**
 * Admin role is required to delete a specific product
 * @summary Delete specific product
 */
export const DeleteProductParams = zod.object({
  "productId": zod.string().describe('The productId parameter in path')
})

export const DeleteProductResponse = zod.void()


/**
 * Partially update specific product
 * @summary Partially update specific product
 */
export const PatchProductParams = zod.object({
  "productId": zod.string().describe('The productId parameter in path')
})

export const PatchProductBody = zod.object({
  "name": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "category_id": zod.string(),
  "brand_id": zod.string(),
  "product_image_id": zod.string(),
  "is_location_offer": zod.boolean(),
  "is_rental": zod.boolean(),
  "co2_rating": zod.string()
})

export const PatchProductResponse = zod.strictObject({
  "success": zod.boolean()
})


/**
 * Retrieve related products
 * @summary Retrieve related products
 */
export const GetRelatedProductsParams = zod.object({
  "productId": zod.string().describe('The productId parameter in path')
})

export const GetRelatedProductsResponseItem = zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "is_location_offer": zod.boolean(),
  "is_rental": zod.boolean(),
  "in_stock": zod.boolean(),
  "co2_rating": zod.string().optional(),
  "is_eco_friendly": zod.boolean(),
  "brand": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "slug": zod.string().optional()
}),
  "category": zod.strictObject({
  "id": zod.string(),
  "parent_id": zod.string().nullish(),
  "name": zod.string(),
  "slug": zod.string().optional(),
  "sub_categories": zod.array(zod.unknown()).optional()
}),
  "product_image": zod.strictObject({
  "by_name": zod.string(),
  "by_url": zod.string(),
  "source_name": zod.string(),
  "source_url": zod.string(),
  "file_name": zod.string(),
  "title": zod.string(),
  "id": zod.string()
}),
  "specs": zod.array(zod.unknown()).optional()
})
export const GetRelatedProductsResponse = zod.array(GetRelatedProductsResponseItem)


/**
 * Search is performed on the `name` column
 * @summary Retrieve specific products matching the search query
 */
export const SearchProductQueryParams = zod.object({
  "q": zod.string().describe('A query phrase'),
  "page": zod.number().optional().describe('pagenumber')
})

export const SearchProductResponse = zod.strictObject({
  "current_page": zod.number(),
  "data": zod.array(zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "is_location_offer": zod.boolean(),
  "is_rental": zod.boolean(),
  "in_stock": zod.boolean(),
  "co2_rating": zod.string(),
  "is_eco_friendly": zod.boolean(),
  "brand": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "slug": zod.string().optional()
}),
  "category": zod.strictObject({
  "id": zod.string(),
  "parent_id": zod.string().nullish(),
  "name": zod.string(),
  "slug": zod.string().optional(),
  "sub_categories": zod.array(zod.unknown()).optional()
}),
  "product_image": zod.strictObject({
  "by_name": zod.string(),
  "by_url": zod.string(),
  "source_name": zod.string(),
  "source_url": zod.string(),
  "file_name": zod.string(),
  "title": zod.string(),
  "id": zod.string()
}),
  "specs": zod.array(zod.unknown()).optional()
})),
  "from": zod.number(),
  "last_page": zod.number(),
  "per_page": zod.number(),
  "to": zod.number(),
  "total": zod.number()
})


/**
 * @summary Retrieve specs for a product
 */
export const GetProductSpecsParams = zod.object({
  "productId": zod.string()
})

export const GetProductSpecsResponseItem = zod.strictObject({
  "id": zod.string(),
  "product_id": zod.string(),
  "spec_name": zod.string(),
  "spec_value": zod.string(),
  "spec_unit": zod.string().nullable()
})
export const GetProductSpecsResponse = zod.array(GetProductSpecsResponseItem)


/**
 * @summary Add a spec to a product
 */
export const StoreProductSpecParams = zod.object({
  "productId": zod.string()
})

export const StoreProductSpecBody = zod.object({
  "spec_name": zod.string(),
  "spec_value": zod.string(),
  "spec_unit": zod.string().nullish()
})

export const StoreProductSpecResponse = zod.strictObject({
  "id": zod.string(),
  "product_id": zod.string(),
  "spec_name": zod.string(),
  "spec_value": zod.string(),
  "spec_unit": zod.string().nullable()
})


/**
 * @summary Retrieve a specific spec
 */
export const GetProductSpecParams = zod.object({
  "productId": zod.string(),
  "specId": zod.string()
})

export const GetProductSpecResponse = zod.strictObject({
  "id": zod.string(),
  "product_id": zod.string(),
  "spec_name": zod.string(),
  "spec_value": zod.string(),
  "spec_unit": zod.string().nullable()
})


/**
 * @summary Update a spec
 */
export const UpdateProductSpecParams = zod.object({
  "productId": zod.string(),
  "specId": zod.string()
})

export const UpdateProductSpecBody = zod.object({
  "spec_name": zod.string(),
  "spec_value": zod.string(),
  "spec_unit": zod.string().nullable()
})

export const UpdateProductSpecResponse = zod.strictObject({
  "success": zod.boolean()
})


/**
 * @summary Delete a spec
 */
export const DeleteProductSpecParams = zod.object({
  "productId": zod.string(),
  "specId": zod.string()
})

export const DeleteProductSpecResponse = zod.void()


/**
 * @summary Retrieve all distinct spec names with their values
 */
export const GetSpecNamesResponse = zod.unknown()


/**
 * `Admin` role is required to get total sales per country
 * @summary Get total sales per country
 */
export const GetTotalSalesPerCountryResponseItem = zod.strictObject({
  "billing_country": zod.string().describe('The billing country'),
  "total_sales": zod.string().describe('Total sales in the country')
})
export const GetTotalSalesPerCountryResponse = zod.array(GetTotalSalesPerCountryResponseItem)


/**
 * `Admin` role is required to get top 10 purchased products
 * @summary Get top 10 purchased products
 */
export const GetTopPurchasedProductsResponseItem = zod.strictObject({
  "name": zod.string().describe('Name of the product'),
  "count": zod.number().describe('Number of times the product was purchased')
})
export const GetTopPurchasedProductsResponse = zod.array(GetTopPurchasedProductsResponseItem)


/**
 * `Admin` role is required to get top 10 best selling categories
 * @summary Get top 10 best selling categories
 */
export const GetBestSellingCategoriesResponseItem = zod.strictObject({
  "category_name": zod.string().describe('Name of the category'),
  "total_earned": zod.string().describe('Total earnings from this category')
})
export const GetBestSellingCategoriesResponse = zod.array(GetBestSellingCategoriesResponseItem)


/**
 * `Admin` role is required to get total sales of years
 * @summary Get total sales of years
 */
export const getTotalSalesOfYearsQueryYearsDefault = 1;

export const GetTotalSalesOfYearsQueryParams = zod.object({
  "years": zod.number().default(getTotalSalesOfYearsQueryYearsDefault).describe('Number of years')
})

export const GetTotalSalesOfYearsResponseItem = zod.strictObject({
  "year": zod.number().describe('Year of the sales data'),
  "total": zod.number().describe('Total sales for the given year')
})
export const GetTotalSalesOfYearsResponse = zod.array(GetTotalSalesOfYearsResponseItem)


/**
 * `Admin` role is required to get average sales per month
 * @summary Get average sales per month
 */
export const getAverageSalesPerMonthQueryYearDefault = 2022;

export const GetAverageSalesPerMonthQueryParams = zod.object({
  "year": zod.number().default(getAverageSalesPerMonthQueryYearDefault).describe('Specific year')
})

export const GetAverageSalesPerMonthResponseItem = zod.strictObject({
  "month": zod.number().describe('Month number (1 for January, 12 for December)'),
  "average": zod.number().describe('Average number of sales for the month'),
  "amount": zod.number().describe('Average sales amount for the month')
})
export const GetAverageSalesPerMonthResponse = zod.array(GetAverageSalesPerMonthResponseItem)


/**
 * `Admin` role is required to get average sales per week
 * @summary Get average sales per week
 */
export const getAverageSalesPerWeekQueryYearDefault = 2022;

export const GetAverageSalesPerWeekQueryParams = zod.object({
  "year": zod.number().default(getAverageSalesPerWeekQueryYearDefault).describe('Specific year')
})

export const GetAverageSalesPerWeekResponseItem = zod.strictObject({
  "week": zod.number().describe('Week number of the year (1-52)'),
  "average": zod.number().describe('Average number of sales for the week'),
  "amount": zod.number().describe('Average sales amount for the week')
})
export const GetAverageSalesPerWeekResponse = zod.array(GetAverageSalesPerWeekResponseItem)


/**
 * `Admin` role is required to get customers by country
 * @summary Get customers by country
 */
export const GetCustomersByCountryResponseItem = zod.strictObject({
  "amount": zod.number().describe('Amount of customers'),
  "country": zod.string().describe('Country')
})
export const GetCustomersByCountryResponse = zod.array(GetCustomersByCountryResponseItem)


/**
 * Generates a TOTP secret and QR code URL for the user to scan and enables TOTP setup.
 * @summary Setup TOTP for the authenticated user
 */
export const SetupTotpResponse = zod.strictObject({
  "secret": zod.string().describe('The TOTP secret key'),
  "qrCodeUrl": zod.string().describe('URL for the QR code')
})


/**
 * Validates the submitted TOTP code and enables TOTP if verification is successful.
 * @summary Verify TOTP code for the authenticated user
 */
export const VerifyTotpBody = zod.object({
  "access_token": zod.string().describe('The user\'s access token'),
  "totp": zod.string().describe('The 6-digit TOTP code')
})

export const VerifyTotpResponse = zod.strictObject({
  "message": zod.string().describe('Success message')
})


/**
 * Retrieve all users
 * @summary Retrieve all users
 */
export const GetUsersQueryParams = zod.object({
  "page": zod.number().optional().describe('pagenumber')
})

export const GetUsersResponse = zod.strictObject({
  "current_page": zod.number(),
  "data": zod.array(zod.strictObject({
  "first_name": zod.string(),
  "last_name": zod.string(),
  "address": zod.strictObject({
  "street": zod.string(),
  "house_number": zod.string().nullable(),
  "city": zod.string(),
  "state": zod.string().nullable(),
  "country": zod.string(),
  "postal_code": zod.string().nullable()
}),
  "phone": zod.string().nullable(),
  "dob": zod.string(),
  "email": zod.string(),
  "id": zod.string(),
  "provider": zod.string().nullable(),
  "totp_enabled": zod.boolean(),
  "enabled": zod.boolean(),
  "failed_login_attempts": zod.number().nullable(),
  "created_at": zod.string()
})),
  "from": zod.number(),
  "last_page": zod.number(),
  "per_page": zod.number(),
  "to": zod.number(),
  "total": zod.number()
})


/**
 * Store new user
 * @summary Store new user
 */
export const storeUserBodyFirstNameMax = 40;

export const storeUserBodyLastNameMax = 20;

export const storeUserBodyAddressStreetMax = 70;

export const storeUserBodyAddressHouseNumberMax = 10;

export const storeUserBodyAddressCityMax = 40;

export const storeUserBodyAddressStateMax = 40;

export const storeUserBodyAddressCountryMax = 40;

export const storeUserBodyAddressPostalCodeMax = 10;

export const storeUserBodyPhoneMax = 24;

export const storeUserBodyPasswordMin = 8;

export const storeUserBodyEmailMax = 256;



export const StoreUserBody = zod.object({
  "first_name": zod.string().max(storeUserBodyFirstNameMax),
  "last_name": zod.string().max(storeUserBodyLastNameMax),
  "address": zod.object({
  "street": zod.string().max(storeUserBodyAddressStreetMax),
  "house_number": zod.string().max(storeUserBodyAddressHouseNumberMax),
  "city": zod.string().max(storeUserBodyAddressCityMax),
  "state": zod.string().max(storeUserBodyAddressStateMax),
  "country": zod.string().max(storeUserBodyAddressCountryMax),
  "postal_code": zod.string().max(storeUserBodyAddressPostalCodeMax)
}).optional(),
  "phone": zod.string().max(storeUserBodyPhoneMax).optional(),
  "dob": zod.iso.date().optional().describe('Must be a valid date between 18 and 75 years ago'),
  "password": zod.string().min(storeUserBodyPasswordMin).describe('Must include uppercase, lowercase, number, and symbol'),
  "email": zod.email().max(storeUserBodyEmailMax)
})

export const StoreUserResponse = zod.strictObject({
  "first_name": zod.string(),
  "last_name": zod.string(),
  "address": zod.strictObject({
  "street": zod.string(),
  "house_number": zod.string().nullable(),
  "city": zod.string(),
  "state": zod.string().nullable(),
  "country": zod.string(),
  "postal_code": zod.string().nullable()
}),
  "phone": zod.string().nullable(),
  "dob": zod.string(),
  "email": zod.string(),
  "id": zod.string(),
  "provider": zod.string().nullable(),
  "totp_enabled": zod.boolean(),
  "enabled": zod.boolean(),
  "failed_login_attempts": zod.number().nullable(),
  "created_at": zod.string()
})


/**
 * @summary Login customer
 */
export const LoginCustomerBody = zod.object({
  "email": zod.string(),
  "password": zod.string()
})

export const LoginCustomerResponse = zod.strictObject({
  "access_token": zod.string(),
  "token_type": zod.string(),
  "expires_in": zod.number()
})


/**
 * Request a new password, it actually sets the password to `welcome02`
 * @summary Request a new password
 */
export const ForgotPasswordBody = zod.object({
  "email": zod.string()
})

export const ForgotPasswordResponse = zod.strictObject({
  "success": zod.boolean()
})


/**
 * Change the existing password to a new one
 * @summary Change password
 */
export const ChangePasswordBody = zod.object({
  "current_password": zod.string(),
  "new_password": zod.string(),
  "new_password_confirmation": zod.string()
})

export const ChangePasswordResponse = zod.strictObject({
  "success": zod.boolean()
})


/**
 * @summary Retrieve current customer info
 */
export const GetCurrentCustomerInfoResponse = zod.strictObject({
  "first_name": zod.string(),
  "last_name": zod.string(),
  "address": zod.strictObject({
  "street": zod.string(),
  "house_number": zod.string().nullable(),
  "city": zod.string(),
  "state": zod.string().nullable(),
  "country": zod.string(),
  "postal_code": zod.string().nullable()
}),
  "phone": zod.string().nullable(),
  "dob": zod.string(),
  "email": zod.string(),
  "id": zod.string(),
  "provider": zod.string().nullable(),
  "totp_enabled": zod.boolean(),
  "enabled": zod.boolean(),
  "failed_login_attempts": zod.number().nullable(),
  "created_at": zod.string()
})


/**
 * Logout - invalidate the token
 * @summary Logout - invalidate the token
 */
export const LogOutResponse = zod.strictObject({
  "message": zod.string()
})


/**
 * Retrieve a refreshed token
 * @summary Retrieve a refreshed token
 */
export const RefreshTokenResponse = zod.strictObject({
  "access_token": zod.string(),
  "token_type": zod.string(),
  "expires_in": zod.number()
})


/**
 * Retrieve specific user
 * @summary Retrieve specific user
 */
export const GetUserParams = zod.object({
  "userId": zod.string().describe('The userId parameter in path')
})

export const GetUserResponse = zod.strictObject({
  "first_name": zod.string(),
  "last_name": zod.string(),
  "address": zod.strictObject({
  "street": zod.string(),
  "house_number": zod.string().nullable(),
  "city": zod.string(),
  "state": zod.string().nullable(),
  "country": zod.string(),
  "postal_code": zod.string().nullable()
}),
  "phone": zod.string().nullable(),
  "dob": zod.string(),
  "email": zod.string(),
  "id": zod.string(),
  "provider": zod.string().nullable(),
  "totp_enabled": zod.boolean(),
  "enabled": zod.boolean(),
  "failed_login_attempts": zod.number().nullable(),
  "created_at": zod.string()
})


/**
 * Update specific user
 * @summary Update specific user
 */
export const UpdateUserParams = zod.object({
  "userId": zod.string().describe('The userId parameter in path')
})

export const updateUserBodyFirstNameMax = 40;

export const updateUserBodyLastNameMax = 20;

export const updateUserBodyAddressStreetMax = 70;

export const updateUserBodyAddressHouseNumberMax = 10;

export const updateUserBodyAddressCityMax = 40;

export const updateUserBodyAddressStateMax = 40;

export const updateUserBodyAddressCountryMax = 40;

export const updateUserBodyAddressPostalCodeMax = 10;

export const updateUserBodyPhoneMax = 24;

export const updateUserBodyPasswordMin = 8;

export const updateUserBodyEmailMax = 256;



export const UpdateUserBody = zod.object({
  "first_name": zod.string().max(updateUserBodyFirstNameMax),
  "last_name": zod.string().max(updateUserBodyLastNameMax),
  "address": zod.object({
  "street": zod.string().max(updateUserBodyAddressStreetMax),
  "house_number": zod.string().max(updateUserBodyAddressHouseNumberMax),
  "city": zod.string().max(updateUserBodyAddressCityMax),
  "state": zod.string().max(updateUserBodyAddressStateMax),
  "country": zod.string().max(updateUserBodyAddressCountryMax),
  "postal_code": zod.string().max(updateUserBodyAddressPostalCodeMax)
}).optional(),
  "phone": zod.string().max(updateUserBodyPhoneMax).optional(),
  "dob": zod.iso.date().optional().describe('Must be a valid date between 18 and 75 years ago'),
  "password": zod.string().min(updateUserBodyPasswordMin).describe('Must include uppercase, lowercase, number, and symbol'),
  "email": zod.email().max(updateUserBodyEmailMax)
})

export const UpdateUserResponse = zod.strictObject({
  "success": zod.boolean()
})


/**
 * Admin role is required to delete a specific user
 * @summary Delete specific user
 */
export const DeleteUserParams = zod.object({
  "userId": zod.string().describe('The userId parameter in path')
})

export const DeleteUserResponse = zod.void()


/**
 * Partially update specific user
 * @summary Partially update specific user
 */
export const PatchUserParams = zod.object({
  "userId": zod.string().describe('The userId parameter in path')
})

export const patchUserBodyFirstNameMax = 40;

export const patchUserBodyLastNameMax = 20;

export const patchUserBodyAddressStreetMax = 70;

export const patchUserBodyAddressHouseNumberMax = 10;

export const patchUserBodyAddressCityMax = 40;

export const patchUserBodyAddressStateMax = 40;

export const patchUserBodyAddressCountryMax = 40;

export const patchUserBodyAddressPostalCodeMax = 10;

export const patchUserBodyPhoneMax = 24;

export const patchUserBodyPasswordMin = 8;

export const patchUserBodyEmailMax = 256;



export const PatchUserBody = zod.object({
  "first_name": zod.string().max(patchUserBodyFirstNameMax),
  "last_name": zod.string().max(patchUserBodyLastNameMax),
  "address": zod.object({
  "street": zod.string().max(patchUserBodyAddressStreetMax),
  "house_number": zod.string().max(patchUserBodyAddressHouseNumberMax),
  "city": zod.string().max(patchUserBodyAddressCityMax),
  "state": zod.string().max(patchUserBodyAddressStateMax),
  "country": zod.string().max(patchUserBodyAddressCountryMax),
  "postal_code": zod.string().max(patchUserBodyAddressPostalCodeMax)
}).optional(),
  "phone": zod.string().max(patchUserBodyPhoneMax).optional(),
  "dob": zod.iso.date().optional().describe('Must be a valid date between 18 and 75 years ago'),
  "password": zod.string().min(patchUserBodyPasswordMin).describe('Must include uppercase, lowercase, number, and symbol'),
  "email": zod.email().max(patchUserBodyEmailMax)
})

export const PatchUserResponse = zod.strictObject({
  "success": zod.boolean()
})


/**
 * Search is performed on the `first_name`, `last_name`, or `city` column
 * @summary Retrieve specific users matching the search query
 */
export const SearchUserQueryParams = zod.object({
  "q": zod.string().describe('A query phrase'),
  "page": zod.number().optional().describe('pagenumber')
})

export const SearchUserResponseItem = zod.strictObject({
  "first_name": zod.string(),
  "last_name": zod.string(),
  "address": zod.strictObject({
  "street": zod.string(),
  "house_number": zod.string().nullable(),
  "city": zod.string(),
  "state": zod.string().nullable(),
  "country": zod.string(),
  "postal_code": zod.string().nullable()
}),
  "phone": zod.string().nullable(),
  "dob": zod.string(),
  "email": zod.string(),
  "id": zod.string(),
  "provider": zod.string().nullable(),
  "totp_enabled": zod.boolean(),
  "enabled": zod.boolean(),
  "failed_login_attempts": zod.number().nullable(),
  "created_at": zod.string()
})
export const SearchUserResponse = zod.array(SearchUserResponseItem)
