export const PAGE_URLS = {
  HOME: '/',
  ACCOUNT: '/account',
  ADMIN_AVERAGE_SALES_PER_MONTH: '/admin/reports/average-sales-per-month',
  ADMIN_AVERAGE_SALES_PER_WEEK: '/admin/reports/average-sales-per-week',
  ADMIN_BRANDS: '/admin/brands',
  ADMIN_CATEGORIES: '/admin/categories',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_MESSAGES: '/admin/messages',
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_STATISTICS: '/admin/reports/statistics',
  ADMIN_USERS: '/admin/users',
  CHECKOUT: '/checkout',
  CONTACT: '/contact',
  FAVORITES: '/account/favorites',
  FORGOT_PASSWORD: '/auth/forgot-password',
  HAND_TOOLS: '/category/hand-tools',
  INVOICES: '/account/invoices',
  LOGIN: '/auth/login',
  MESSAGES: '/account/messages',
  OTHER: '/category/other',
  POWER_TOOLS: '/category/power-tools',
  PRODUCT: '/product',
  PROFILE: '/account/profile',
  REGISTER: '/auth/register',
  RENTALS: '/rentals',
  SPECIAL_TOOLS: '/category/special-tools',
} as const;

export type PageUrl = (typeof PAGE_URLS)[keyof typeof PAGE_URLS];
